### PR TITLE
Imdbratings

### PR DESCRIPTION
**Pull request by reach2jeyan**

### CODE REVIEW

**Comment by reach2jeyan** [comment]
@divhegde Can you check how or whether, can the below code in the step definition, be made generic? Like the `browser_url` code? 

```
`Then(/^I print the text with class$/) do
 +  weather = browser.div(:data_attrid => "kc:/location/citytown:current weather").text
 +  puts weather`
```

**Comment by divhegde** [comment]
for what data do you want it to be made re-usable? Like weather, you want it to print population, local time etc?

**Comment by reach2jeyan** [comment]
My requirement is,

I was thinking, if I need to define, each time, the step, by giving the class path, in the step definition. Suppose, If I can give the class path or class name in the gherkin in `feature file` and then re-use the standard ruby code, for class to print the info.

For eg: 

```
`Then(/^I print the text with class$/) do
 +  weather = browser.div(:data_attrid => "kc:/location/citytown:current weather").text
 +  puts weather
````

This prints the weather in the terminal. Next time, I might be using this `data_attrid` for printing some other element. So Instead of again defining the path in the `step definiton` could I directly give the `path` name in the features and call this code?  

Clear?

**Comment by divhegde** [comment]
Replace data_input with below in your feature file, you will get correct data
statistical_region:population
citytown:local time
citytown:current weather

Then(/^I print the text with class ([^"]*)$/) do |data_input|
    weather = browser.div(:data_attrid => "kc:/location/#{data_input}").text
    puts weather
  end

**Comment by reach2jeyan** [comment]
I didnt get you! What exactly to be replaced? How should my test step be written like? 

`Then I print the text with ""kc:/location/#{data_input}"` ?? 

or should it be like this

`Then I print the text with "Statistical_region:population"`

Examples:
|Statistical_regision:population|
|class name|

**Comment by reach2jeyan** [comment]
@divhegde  Looks good?

`Then I enter "kc:/location/citytown:current weather" in data_attribute and print content`

Now the next time you find any element in any page with `data_attrib`, that need to be printed text, we can re-use this by just changing the `class name` in the double quotes.

Let me know if this is generic, like how you enter the resource path in paypal in feature files, or can this be more improved?

```
Then(/^I enter "([^"]*)" in data_attribute and print content$/) do |data_attribute|
  data = browser.div(:data_attrid => data_attribute).text
  puts data
end
```

**Pull request merged**
